export const colorsList = [
  { id: 1, name: 'Червоний', styleClass: 'red' },
  { id: 2, name: 'Рожевий', styleClass: 'pink' },
  { id: 3, name: 'Помаранчевий', styleClass: 'orange' },
  { id: 4, name: 'Жовтий', styleClass: 'yellow' },
  { id: 5, name: 'Коричневий', styleClass: 'brown' },
  { id: 6, name: 'Синій', styleClass: 'blue' },
  { id: 7, name: 'Блакитний', styleClass: 'cyan' },
  { id: 8, name: 'Бежевий', styleClass: 'beige' },
  { id: 9, name: 'Бірюзовий', styleClass: 'turquoise' },
  { id: 10, name: 'Чорний', styleClass: 'black' },
  { id: 11, name: 'Фіолетовий', styleClass: 'purple' },
  { id: 12, name: 'Сірий', styleClass: 'grey' },
  { id: 13, name: 'Білий', styleClass: 'white' },
  { id: 14, name: 'Золотистий', styleClass: 'gold' },
  { id: 15, name: 'Перламутровий', styleClass: 'pearly' },
  { id: 16, name: 'Мідний', styleClass: 'copper' },
  { id: 17, name: 'Прозорий', styleClass: 'transparent' },
  { id: 18, name: 'Зелений', styleClass: 'green' },
  { id: 19, name: 'Сріблястий', styleClass: 'silver' },
  { id: 20, name: 'Різнокольоровий', styleClass: 'multicoloured' },
];
